plugins:
    - jekyll-redirect-from
    - jekyll-sitemap

# Site settings
title: allegro.tech
menu: false
future: true
description: "We use Open Source solutions on a daily basis here at Allegro Group. Why not work on our karma and give something in return? Welcome to our open source technology blog."
name: allegro.tech
baseurl: ""
url: "https://allegro.tech"
twitter_username: allegrotech
github_username:  allegro
facebook_username: allegro.tech
google_plus_id: +AllegroTechBlog
meetup_username: allegrotech
slideshare_username: allegrotech
timezone: Europe/Warsaw

kramdown:
    input: GFM
    hard_wrap: false
    coderay_line_numbers: nil

sass:
    sass_dir: css/partials

permalink: /:year/:month/:title.html

collections:
  events:
    output: true
    permalink: /events/:name
